"""Cases generated from the corpus by tools/build_cases.py.

Do not edit by hand: regenerate after changing the corpus. Each entry
is a sentence a fault file says that fault arrives as, so the label is
the fault the sentence was written under.
"""

from __future__ import annotations

from typing import List

from chat_cases import Case

# 260 cases, harvested from 1064 quoted sentences.
GENERATED: List[Case] = [
    Case("lò vi sóng sau lò không thấy gió ra", "diagnose", "microwave_oven", ["MW_FAN_NOISY"]),
    Case("quạt trần kêu ù ù", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("ấm đun nước công tắc ấm không giữ", "diagnose", "kettle", ["KETTLE_SWITCH"]),
    Case("vòi nước nước không mạnh như trước", "diagnose", "faucet", ["FAUCET_LOW_FLOW"]),
    Case("bếp gas lâu sôi lắm", "diagnose", "gas_stove", ["STOVE_BURNER_CLOGGED"]),
    Case("cắm điện nghe xẹt một cái", "diagnose", "electric_fan", ["FAN_CORD_DAMAGE"]),
    Case("lò vi sóng đóng cửa mà lò không chạy", "diagnose", "microwave_oven", ["MW_DOOR_SWITCH"]),
    Case("lò vi sóng nghe tạch tạch trong lò", "diagnose", "microwave_oven", ["MW_SPARKING"]),
    Case("máy giặt vào được một ít rồi dừng", "diagnose", "washing_machine", ["WM_NO_WATER_INLET"]),
    Case("quạt đứng không vững", "diagnose", "electric_fan", ["FAN_WOBBLE"]),
    Case("tủ lạnh cái nút ở khung cửa bị kẹt", "diagnose", "refrigerator", ["FRIDGE_LIGHT_FAULT"]),
    Case("quạt trần rung", "diagnose", "ceiling_fan", ["CEILFAN_MOUNT_LOOSE"]),
    Case("tivi không bật được", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("bóng đèn máng đèn có nước", "diagnose", "light_bulb", ["LIGHT_FIXTURE_LEAK"]),
    Case("máy nước nóng may so hỏng", "diagnose", "water_heater", ["WH_HEATING_ELEMENT"]),
    Case("đường ống nước nước phun trong tường", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("ổ cắm điện cắm vào nghe cái bụp", "diagnose", "power_outlet", ["OUTLET_SHORT_CIRCUIT"]),
    Case("ấm đun nước ấm hết đời rồi hả em", "diagnose", "kettle", ["KETTLE_HEATING_BASE"]),
    Case("tivi có cái vệt đen cứ lan ra", "diagnose", "television", ["TV_PANEL_DAMAGE"]),
    Case("bồn cầu xả yếu", "diagnose", "toilet", ["TOILET_FILL_VALVE"]),
    Case("quạt điện tối qua ngủ dậy thấy mùi khét trong phòng", "diagnose", "electric_fan", ["FAN_MOTOR_BURNT"]),
    Case("quạt điện quạt kêu rè rè", "diagnose", "electric_fan", ["FAN_WORN_BEARING"]),
    Case("lò vi sóng cắm vào nghe cái bụp rồi tắt", "diagnose", "microwave_oven", ["MW_NO_POWER"]),
    Case("chuyển nhà xong tivi bị vệt", "diagnose", "television", ["TV_PANEL_DAMAGE"]),
    Case("quạt trần yếu xìu", "diagnose", "ceiling_fan", ["CEILFAN_CAPACITOR"]),
    Case("bóng đèn đèn nhà em đi rồi", "diagnose", "light_bulb", ["LIGHT_BULB_DEAD"]),
    Case("vòi nước đáy tủ bị phồng", "diagnose", "faucet", ["FAUCET_BASE_LEAK"]),
    Case("ấm đun nước đáy ấm chảy nước", "diagnose", "kettle", ["KETTLE_LEAK"]),
    Case("vòi nước nước chảy như nước mắt", "diagnose", "faucet", ["FAUCET_LOW_FLOW"]),
    Case("may lanh nhieu nuoc", "diagnose", "air_conditioner", ["AC_DRAIN_BLOCKED"]),
    Case("đường ống nước nước phun ra", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("bóng đèn đèn sáng yếu", "diagnose", "light_bulb", ["LIGHT_DIM"]),
    Case("lò nướng quá nóng", "diagnose", "oven", ["OVEN_THERMOSTAT"]),
    Case("bóng đèn phòng tối quá", "diagnose", "light_bulb", ["LIGHT_DIM"]),
    Case("ấm đun nước cắm vào không thấy gì", "diagnose", "kettle", ["KETTLE_HEATING_BASE"]),
    Case("bồn cầu nghe tiếng rít khi nước vào", "diagnose", "toilet", ["TOILET_FILL_VALVE"]),
    Case("bồn cầu ngồi thấy nó lắc", "diagnose", "toilet", ["TOILET_SEAT_BROKEN"]),
    Case("lò vi sóng xẹt lửa", "diagnose", "microwave_oven", ["MW_SPARKING"]),
    Case("bếp gas phải đè tay xuống", "diagnose", "gas_stove", ["STOVE_FLAME_OUT"]),
    Case("lò nướng nướng gà mà mặt dưới trắng hếu", "diagnose", "oven", ["OVEN_HEATING_ELEMENT"]),
    Case("tivi không nhận điều khiển", "diagnose", "television", ["TV_REMOTE_FAULT"]),
    Case("lò nướng màn hình lò nhấp nháy", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("tivi không dò được kênh", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("quạt điện quạt không quay đầu", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("bồn cầu két nước chảy hoài", "diagnose", "toilet", ["TOILET_FLAPPER_LEAK"]),
    Case("quạt trần phải bật số 3 mới chạy", "diagnose", "ceiling_fan", ["CEILFAN_CAPACITOR"]),
    Case("đường ống nước tường bị ẩm", "diagnose", "water_pipe", ["PIPE_JOINT_LEAK"]),
    Case("đường ống nước nghe tiếng nước chảy trong tường ban đêm", "diagnose", "water_pipe", ["PIPE_NOISY"]),
    Case("lò nướng lò không đủ nóng", "diagnose", "oven", ["OVEN_THERMOSTAT"]),
    Case("đường ống nước nước bị đục", "diagnose", "water_pipe", ["PIPE_RUSTY_WATER"]),
    Case("đường ống nước tường nhà em kêu răng rắc khi mở nước", "diagnose", "water_pipe", ["PIPE_NOISY"]),
    Case("ấm siêu tốc không ngắt", "diagnose", "kettle", ["KETTLE_THERMOSTAT"]),
    Case("đường ống nước nước không xuống", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("vòi nước gạt vòi nặng lắm", "diagnose", "faucet", ["FAUCET_CARTRIDGE"]),
    Case("quạt điện quạt kêu và rung", "diagnose", "electric_fan", ["FAN_WOBBLE"]),
    Case("quạt trần có mùi cháy trong phòng mà không biết ở đâu", "diagnose", "ceiling_fan", ["CEILFAN_MOTOR_BURNT"]),
    Case("hôm qua sét đánh xong tivi không lên", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("lò vi sóng trong lò có tia lửa", "diagnose", "microwave_oven", ["MW_SPARKING"]),
    Case("lò vi sóng ồn hơn trước", "diagnose", "microwave_oven", ["MW_FAN_NOISY"]),
    Case("ống nước bung rồi", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("tivi dở chứng", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("bồn cầu nghe róc rách cả đêm không ngủ được", "diagnose", "toilet", ["TOILET_FLAPPER_LEAK"]),
    Case("ấm đun nước chạm vào ấm thấy tê", "diagnose", "kettle", ["KETTLE_LEAK"]),
    Case("xả máy giặt là nước trào lên bồn rửa", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("lò nướng quạt lò không chạy", "diagnose", "oven", ["OVEN_FAN_FAULT"]),
    Case("tivi chậm rì", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("tivi mất tiếng", "diagnose", "television", ["TV_NO_SOUND"]),
    Case("lò nướng chỉ có thanh trên đỏ", "diagnose", "oven", ["OVEN_HEATING_ELEMENT"]),
    Case("đường ống nước nhà em thành sông", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("quạt điện cái nút đảo bấm không ăn", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("bật máy giặt là cúp điện", "diagnose", "power_outlet", ["OUTLET_TRIPS_BREAKER"]),
    Case("bếp gas không có lửa", "diagnose", "gas_stove", ["STOVE_IGNITER"]),
    Case("vòi nước vòi nhỏ giọt", "diagnose", "faucet", ["FAUCET_DRIP"]),
    Case("chân bồn cầu bị rò", "diagnose", "toilet", ["TOILET_BASE_LEAK"]),
    Case("lò vi sóng quay ầm ầm mà lạnh ngắt", "diagnose", "microwave_oven", ["MW_MAGNETRON"]),
    Case("bếp gas buông tay ra là tắt", "diagnose", "gas_stove", ["STOVE_FLAME_OUT"]),
    Case("vòi nước lõi vòi hỏng", "diagnose", "faucet", ["FAUCET_CARTRIDGE"]),
    Case("ổ cắm điện át nhà em nhảy hoài", "diagnose", "power_outlet", ["OUTLET_TRIPS_BREAKER"]),
    Case("tivi tắt ngúm", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("bồn cầu nhà em khóc suốt", "diagnose", "toilet", ["TOILET_FLAPPER_LEAK"]),
    Case("tivi không vào điện", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("quạt trần quay như rùa", "diagnose", "ceiling_fan", ["CEILFAN_CAPACITOR"]),
    Case("bếp gas bình mới mà không có gas", "diagnose", "gas_stove", ["STOVE_REGULATOR"]),
    Case("lò vi sóng mâm xoay bị kẹt", "diagnose", "microwave_oven", ["MW_TURNTABLE_MOTOR"]),
    Case("lò nướng vặn núm mà lò không lên", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("chân bồn cầu bị thấm", "diagnose", "toilet", ["TOILET_BASE_LEAK"]),
    Case("bồn cầu đầy nước", "diagnose", "toilet", ["TOILET_CLOGGED"]),
    Case("đường ống nước có vệt nước trên trần", "diagnose", "water_pipe", ["PIPE_JOINT_LEAK"]),
    Case("lò nướng nướng lâu hơn công thức", "diagnose", "oven", ["OVEN_THERMOSTAT"]),
    Case("bóng đèn đèn không sáng như trước", "diagnose", "light_bulb", ["LIGHT_DIM"]),
    Case("đường ống nước nước có lợn cợn", "diagnose", "water_pipe", ["PIPE_RUSTY_WATER"]),
    Case("quạt trần nhà em hết hơi rồi", "diagnose", "ceiling_fan", ["CEILFAN_CAPACITOR"]),
    Case("đường ống nước nước chảy ào ào", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("bóng đèn thay bóng mới mà vẫn tối", "diagnose", "light_bulb", ["LIGHT_DIM"]),
    Case("máy giặt kéo gioăng ra thấy nứt", "diagnose", "washing_machine", ["WM_DOOR_SEAL_LEAK"]),
    Case("quạt trần quay chậm và kêu", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("đường ống nước gạch bị bong", "diagnose", "water_pipe", ["PIPE_JOINT_LEAK"]),
    Case("bếp gas nấu lâu lắm", "diagnose", "gas_stove", ["STOVE_BURNER_CLOGGED"]),
    Case("đường ống nước giặt quần áo trắng bị ố vàng", "diagnose", "water_pipe", ["PIPE_RUSTY_WATER"]),
    Case("lò vi sóng lò chạy bình thường mà không ăn thua", "diagnose", "microwave_oven", ["MW_MAGNETRON"]),
    Case("quạt trần chỉ có một tốc độ thôi", "diagnose", "ceiling_fan", ["CEILFAN_SPEED_SWITCH"]),
    Case("quạt trần chạy như không chạy", "diagnose", "ceiling_fan", ["CEILFAN_CAPACITOR"]),
    Case("nắp bồn cầu ố vàng", "diagnose", "toilet", ["TOILET_SEAT_BROKEN"]),
    Case("quạt điện nút đảo bị kẹt", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("ổ cắm điện cả phòng mất điện", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("ấm đun nước sôi ùng ục mà cứ đun", "diagnose", "kettle", ["KETTLE_THERMOSTAT"]),
    Case("ổ điện chết", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("ống nước bị rò", "diagnose", "water_pipe", ["PIPE_JOINT_LEAK"]),
    Case("bồn cầu nhà em yếu xìu", "diagnose", "toilet", ["TOILET_WEAK_FLUSH"]),
    Case("đường ống nước sơn tường bị phồng", "diagnose", "water_pipe", ["PIPE_JOINT_LEAK"]),
    Case("bóng đèn công tắc bị đen", "diagnose", "light_bulb", ["LIGHT_SWITCH_FAULT"]),
    Case("ổ cắm bị gãy", "diagnose", "power_outlet", ["OUTLET_BROKEN_FACE"]),
    Case("bóng đèn đèn vẫn sáng mờ khi đã tắt", "diagnose", "light_bulb", ["LIGHT_FLICKERING"]),
    Case("bồn cầu trần nhà dưới bị ố", "diagnose", "toilet", ["TOILET_BASE_LEAK"]),
    Case("ổ cắm điện cúp điện hoài", "diagnose", "power_outlet", ["OUTLET_TRIPS_BREAKER"]),
    Case("ổ cắm toé lửa", "diagnose", "power_outlet", ["OUTLET_SHORT_CIRCUIT"]),
    Case("lò nướng lò nhà em nóng quá tay", "diagnose", "oven", ["OVEN_THERMOSTAT"]),
    Case("quạt điện quạt bị đơ", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("vỡ ống nước", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("lò nướng lò nhà em chỉ nóng có nửa", "diagnose", "oven", ["OVEN_HEATING_ELEMENT"]),
    Case("lò nướng sờ cửa lò bỏng tay", "diagnose", "oven", ["OVEN_DOOR_GLASS"]),
    Case("bồn rửa ống cong dưới bồn bị nứt", "diagnose", "sink", ["SINK_TRAP_LEAK"]),
    Case("lò vi sóng mâm không quay", "diagnose", "microwave_oven", ["MW_TURNTABLE_MOTOR"]),
    Case("bồn cầu không đi được", "diagnose", "toilet", ["TOILET_CLOGGED"]),
    Case("bồn rửa mùi cống bốc lên", "diagnose", "sink", ["SINK_SMELL"]),
    Case("mấy ổ liền nhau không có điện", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("đường ống nước nước lên ngược", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("chỗ này không có điện", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("quạt trần chiết áp hỏng", "diagnose", "ceiling_fan", ["CEILFAN_SPEED_SWITCH"]),
    Case("quạt trần kêu ken két cả đêm", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("quạt đứng im một chỗ", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("vòi nước tắm mà như mưa phùn", "diagnose", "faucet", ["FAUCET_LOW_FLOW"]),
    Case("ấm đun nước đáy ấm bị vôi", "diagnose", "kettle", ["KETTLE_SCALE"]),
    Case("bồn rửa cái vành thoát bị mục ra", "diagnose", "sink", ["SINK_DRAIN_CORRODED"]),
    Case("máy lạnh gạt tay thì quạt chạy", "diagnose", "air_conditioner", ["AC_CAPACITOR"]),
    Case("đường ống nước áp lực nước yếu", "diagnose", "water_pipe", ["PIPE_LOW_PRESSURE"]),
    Case("bồn cầu lau khô rồi lại ướt", "diagnose", "toilet", ["TOILET_BASE_LEAK"]),
    Case("bồn cầu nước cứ vào hoài không dừng", "diagnose", "toilet", ["TOILET_FILL_VALVE"]),
    Case("tivi rì mốt hỏng", "diagnose", "television", ["TV_REMOTE_FAULT"]),
    Case("cúp điện xong tivi hỏng luôn", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("tivi im re", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("lò nướng bảng điều khiển lò đơ", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("ấm đun nước ấm sôi rồi không nhảy", "diagnose", "kettle", ["KETTLE_THERMOSTAT"]),
    Case("bồn rửa bốc mùi", "diagnose", "sink", ["SINK_SMELL"]),
    Case("rửa bát xong nước đọng cả buổi", "diagnose", "sink", ["SINK_CLOGGED"]),
    Case("bếp gas bình còn gas mà lửa nhỏ", "diagnose", "gas_stove", ["STOVE_REGULATOR"]),
    Case("đường ống nước tường nhà em cứ ẩm hoài", "diagnose", "water_pipe", ["PIPE_JOINT_LEAK"]),
    Case("bóng đèn bật hoài không lên", "diagnose", "light_bulb", ["LIGHT_BULB_DEAD"]),
    Case("quạt trần không mát như trước", "diagnose", "ceiling_fan", ["CEILFAN_CAPACITOR"]),
    Case("bồn cầu tắc cống", "diagnose", "toilet", ["TOILET_CLOGGED"]),
    Case("bồn cầu nhà vệ sinh có mùi hôi", "diagnose", "toilet", ["TOILET_BASE_LEAK"]),
    Case("quạt điện quạt như sắp rớt", "diagnose", "electric_fan", ["FAN_WOBBLE"]),
    Case("ổ cắm điện tự nhiên mất điện một khu", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("lò nướng may so lò bị đứt", "diagnose", "oven", ["OVEN_HEATING_ELEMENT"]),
    Case("quạt điện quạt đảo giật cục", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("quạt điện ngửi thấy mùi cháy ở chỗ quạt", "diagnose", "electric_fan", ["FAN_MOTOR_BURNT"]),
    Case("quạt điện quạt yếu hẳn", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("quạt điện quạt khô dầu", "diagnose", "electric_fan", ["FAN_WORN_BEARING"]),
    Case("nắp bồn cầu lỏng", "diagnose", "toilet", ["TOILET_SEAT_BROKEN"]),
    Case("ấm đun nước ấm đun mãi không sôi", "diagnose", "kettle", ["KETTLE_HEATING_BASE"]),
    Case("quạt trần lắc lư", "diagnose", "ceiling_fan", ["CEILFAN_MOUNT_LOOSE"]),
    Case("lò vi sóng lò không quay nữa", "diagnose", "microwave_oven", ["MW_TURNTABLE_MOTOR"]),
    Case("quạt điện quạt kêu như cối xay", "diagnose", "electric_fan", ["FAN_WORN_BEARING"]),
    Case("quạt trần kêu lạo xạo", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("ấm đun nước ấm chạy mà không nóng", "diagnose", "kettle", ["KETTLE_HEATING_BASE"]),
    Case("ngửi thấy mùi gas", "diagnose", "gas_stove", ["STOVE_GAS_LEAK"]),
    Case("bồn cầu nhà em bị đầy", "diagnose", "toilet", ["TOILET_CLOGGED"]),
    Case("đường ống nước tường kêu khi mở nước", "diagnose", "water_pipe", ["PIPE_NOISY"]),
    Case("lò vi sóng chốt cửa bị gãy", "diagnose", "microwave_oven", ["MW_DOOR_SWITCH"]),
    Case("máy nước nóng phải nhấn nút đỏ", "diagnose", "water_heater", ["WH_THERMOSTAT"]),
    Case("quạt điện quạt quay chậm", "diagnose", "electric_fan", ["FAN_WORN_BEARING"]),
    Case("bóng đèn đèn có mùi khét", "diagnose", "light_bulb", ["LIGHT_FIXTURE_LEAK"]),
    Case("bếp gas lửa tắt ngang", "diagnose", "gas_stove", ["STOVE_FLAME_OUT"]),
    Case("ấm đun nước ấm bị rỉ nước", "diagnose", "kettle", ["KETTLE_LEAK"]),
    Case("máy giặt rút điện rồi nước vẫn vào", "diagnose", "washing_machine", ["WM_OVERFLOW"]),
    Case("quạt điện quạt ù ù mà không chạy", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("bếp gas cái nút vặn bếp bị cứng", "diagnose", "gas_stove", ["STOVE_VALVE_STUCK"]),
    Case("vòi nước nước chảy rỉ rả", "diagnose", "faucet", ["FAUCET_LOW_FLOW"]),
    Case("quạt trần kêu cót két", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("bếp gas không nổ lửa", "diagnose", "gas_stove", ["STOVE_IGNITER"]),
    Case("bóng đèn công tắc nhà em đơ", "diagnose", "light_bulb", ["LIGHT_SWITCH_FAULT"]),
    Case("quạt điện quạt chập chờn", "diagnose", "electric_fan", ["FAN_CORD_DAMAGE"]),
    Case("ấm đun nước nước chưa sôi ấm đã tắt", "diagnose", "kettle", ["KETTLE_THERMOSTAT"]),
    Case("quạt trần nghe cọt kẹt suốt đêm", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("bóng đèn đèn sáng rồi tắt", "diagnose", "light_bulb", ["LIGHT_FLICKERING"]),
    Case("đường ống nước nước nhà em èo uột", "diagnose", "water_pipe", ["PIPE_LOW_PRESSURE"]),
    Case("bồn cầu vữa bị mủn", "diagnose", "toilet", ["TOILET_BASE_LEAK"]),
    Case("vòi nước gạt hết cỡ vẫn chảy", "diagnose", "faucet", ["FAUCET_CARTRIDGE"]),
    Case("bếp gas bấm không cháy", "diagnose", "gas_stove", ["STOVE_IGNITER"]),
    Case("bồn rửa chén hôi quá", "diagnose", "sink", ["SINK_SMELL"]),
    Case("tivi nhà em hết tiếng rồi", "diagnose", "television", ["TV_NO_SOUND"]),
    Case("lò vi sóng lò kêu lạch cạch", "diagnose", "microwave_oven", ["MW_FAN_NOISY"]),
    Case("cục pin trong cục nóng hỏng", "diagnose", "air_conditioner", ["AC_CAPACITOR"]),
    Case("lò vi sóng mâm quay được một lúc rồi dừng", "diagnose", "microwave_oven", ["MW_TURNTABLE_MOTOR"]),
    Case("đường ống nước nghe ọc ọc trong ống", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("ấm đun nước cái nút gạt không ăn", "diagnose", "kettle", ["KETTLE_SWITCH"]),
    Case("lò nướng quạt trong lò kêu rít", "diagnose", "oven", ["OVEN_FAN_FAULT"]),
    Case("quạt điện quạt nóng quá", "diagnose", "electric_fan", ["FAN_MOTOR_BURNT"]),
    Case("là mất điện cả nhà hay chỉ một khu vực ạ, và hàng xóm có mất không?", "diagnose", "power_outlet", ["OUTLET_TRIPS_BREAKER"]),
    Case("đường ống nước nước đục như sữa", "diagnose", "water_pipe", ["PIPE_RUSTY_WATER"]),
    Case("tivi cứ tắt rồi bật", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("bồn rửa cái lưới thoát bị mục", "diagnose", "sink", ["SINK_DRAIN_CORRODED"]),
    Case("ấm đun nước gạt công tắc không giữ", "diagnose", "kettle", ["KETTLE_THERMOSTAT"]),
    Case("lò vi sóng lò nóng vỏ", "diagnose", "microwave_oven", ["MW_FAN_NOISY"]),
    Case("bóng đèn đèn nhà em nhấp nháy như vũ trường", "diagnose", "light_bulb", ["LIGHT_FLICKERING"]),
    Case("lò nướng cửa lò không mở được", "diagnose", "oven", ["OVEN_DOOR_GLASS"]),
    Case("quạt điện quạt kêu to", "diagnose", "electric_fan", ["FAN_WORN_BEARING"]),
    Case("bồn cầu nghẹt bàn cầu", "diagnose", "toilet", ["TOILET_CLOGGED"]),
    Case("lò nướng hẹn giờ lò không chạy", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("bóng đèn phải bấm mạnh mới sáng", "diagnose", "light_bulb", ["LIGHT_SWITCH_FAULT"]),
    Case("máy giặt lúc được lúc không", "diagnose", "washing_machine", ["WM_PCB_FAULT"]),
    Case("lò vi sóng cửa lò bị xệ", "diagnose", "microwave_oven", ["MW_DOOR_SWITCH"]),
    Case("lò nướng nướng hai khay thì khay dưới không chín", "diagnose", "oven", ["OVEN_FAN_FAULT"]),
    Case("đường ống nước nước đọng hoài không rút", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("máy lạnh may loc nuoc", "diagnose", "air_conditioner", ["AC_DRAIN_BLOCKED"]),
    Case("quạt trần có mùi cháy mà không biết ở đâu", "diagnose", "ceiling_fan", ["CEILFAN_MOTOR_BURNT"]),
    Case("bồn cầu lung lay", "diagnose", "toilet", ["TOILET_BASE_LEAK"]),
    Case("lò vi sóng lò im re", "diagnose", "microwave_oven", ["MW_NO_POWER"]),
    Case("máy giặt vệt đen bám vào đồ", "diagnose", "washing_machine", ["WM_SMELL_MOLD"]),
    Case("quạt trần nằm dưới mà không dám ngủ", "diagnose", "ceiling_fan", ["CEILFAN_MOUNT_LOOSE"]),
    Case("quạt điện cánh quạt đảo", "diagnose", "electric_fan", ["FAN_WOBBLE"]),
    Case("quạt điện quạt phải lấy tay quay mới chạy", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("bếp gas lửa phù phù", "diagnose", "gas_stove", ["STOVE_BURNER_CLOGGED"]),
    Case("tivi mất hết kênh", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("quạt trần cái điều tốc hỏng", "diagnose", "ceiling_fan", ["CEILFAN_SPEED_SWITCH"]),
    Case("tivi màn hình đen như tắt", "diagnose", "television", ["TV_BACKLIGHT"]),
    Case("lò vi sóng hâm mãi không nóng", "diagnose", "microwave_oven", ["MW_MAGNETRON"]),
    Case("bồn cầu nước chảy cả đêm", "diagnose", "toilet", ["TOILET_FLAPPER_LEAK"]),
    Case("ổ cắm lúc có lúc không", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("ổ cắm điện cái ổ này chết rồi", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("tủ lạnh dưới khay rau có lớp đá", "diagnose", "refrigerator", ["FRIDGE_DRAIN_BLOCKED"]),
    Case("quạt điện dây quạt bị nứt cổ gà", "diagnose", "electric_fan", ["FAN_CORD_DAMAGE"]),
    Case("máy lạnh bấm nút trên máy thì chạy", "diagnose", "air_conditioner", ["AC_REMOTE_FAULT"]),
    Case("quạt điện quạt kêu lạo xạo", "diagnose", "electric_fan", ["FAN_WORN_BEARING"]),
    Case("đường ống nước cống bốc mùi", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("bồn cầu lâu đầy nước", "diagnose", "toilet", ["TOILET_FILL_VALVE"]),
    Case("bếp gas Không đánh lửa", "diagnose", "gas_stove", ["STOVE_IGNITER"]),
    Case("ổ cắm điện cắm nhiều thứ quá bị nhảy điện", "diagnose", "power_outlet", ["OUTLET_OVERLOAD"]),
    Case("tivi bị câm", "diagnose", "television", ["TV_NO_SOUND"]),
    Case("bếp gas vặn nặng tay", "diagnose", "gas_stove", ["STOVE_VALVE_STUCK"]),
    Case("ổ cắm điện mất điện một khu", "diagnose", "power_outlet", ["OUTLET_TRIPS_BREAKER"]),
    Case("nghe mùi gas", "diagnose", "gas_stove", ["STOVE_GAS_LEAK"]),
    Case("bóng đèn máng đèn bị rỉ", "diagnose", "light_bulb", ["LIGHT_FIXTURE_LEAK"]),
    Case("lò nướng quạt vẫn chạy sau khi tắt lò", "diagnose", "oven", ["OVEN_FAN_FAULT"]),
    Case("bồn cầu nước lên tới miệng rồi", "diagnose", "toilet", ["TOILET_CLOGGED"]),
    Case("bồn rửa vành lỗ thoát bị ố", "diagnose", "sink", ["SINK_DRAIN_CORRODED"]),
    Case("quạt điện quạt quay chậm rì", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("lò vi sóng bấm nút không ăn gì", "diagnose", "microwave_oven", ["MW_NO_POWER"]),
    Case("bếp gas van không khớp bình", "diagnose", "gas_stove", ["STOVE_REGULATOR"]),
    Case("bồn rửa giỏ thoát bị lỏng", "diagnose", "sink", ["SINK_DRAIN_CORRODED"]),
    Case("quạt điện dây quạt tróc vỏ", "diagnose", "electric_fan", ["FAN_CORD_DAMAGE"]),
    Case("máy giặt xả xong nghe đập trong tường", "diagnose", "water_pipe", ["PIPE_NOISY"]),
    Case("quạt điện quạt nó bò", "diagnose", "electric_fan", ["FAN_WOBBLE"]),
    Case("bồn cầu cái vòng ngồi bị nứt", "diagnose", "toilet", ["TOILET_SEAT_BROKEN"]),
    Case("bồn rửa ống thoát dưới bồn bị rỉ", "diagnose", "sink", ["SINK_TRAP_LEAK"]),
    Case("tivi bị loạn", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("quạt điện mùi khê khê", "diagnose", "electric_fan", ["FAN_MOTOR_BURNT"]),
    Case("bếp gas bếp không lên lửa", "diagnose", "gas_stove", ["STOVE_IGNITER"]),
    Case("bóng đèn phải bấm kiểu gì đó nó mới lên", "diagnose", "light_bulb", ["LIGHT_SWITCH_FAULT"]),
    Case("đường ống nước nhà tắm lúc nào cũng ướt", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
]
