"""Cases generated from the corpus by tools/build_cases.py.

Do not edit by hand: regenerate after changing the corpus. Each entry
is a sentence a fault file says that fault arrives as, so the label is
the fault the sentence was written under.
"""

from __future__ import annotations

from typing import List

from chat_cases import Case

# 400 cases, harvested from 1425 quoted sentences.
GENERATED: List[Case] = [
    Case("máy rửa bát cốc thuỷ tinh ra mờ đục hết", "diagnose", "dishwasher", ["DW_NOT_CLEAN"]),
    Case("đường ống nước xì nước mạnh", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("phích cắm tụt ra", "diagnose", "power_outlet", ["OUTLET_LOOSE_CONTACT"]),
    Case("tivi bấm mãi không lên", "diagnose", "television", ["TV_REMOTE_FAULT"]),
    Case("lavabo hôi mà lau mãi không hết", "diagnose", "sink", ["SINK_SMELL"]),
    Case("ổ cắm điện thiết bị chập chờn", "diagnose", "power_outlet", ["OUTLET_LOOSE_CONTACT"]),
    Case("quạt điện đảo gió không ăn", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("bóng đèn cái nút bật đèn liệt rồi", "diagnose", "light_bulb", ["LIGHT_SWITCH_FAULT"]),
    Case("đường ống nước tường nhà em cứ ẩm hoài", "diagnose", "water_pipe", ["PIPE_JOINT_LEAK"]),
    Case("may rua bat khong vao nuoc", "diagnose", "dishwasher", ["DW_NO_WATER"]),
    Case("lò vi sóng lò chạy cho vui thôi", "diagnose", "microwave_oven", ["MW_MAGNETRON"]),
    Case("bếp gas núm cứng quá", "diagnose", "gas_stove", ["STOVE_VALVE_STUCK"]),
    Case("quạt bị rò điện", "diagnose", "electric_fan", ["FAN_CORD_DAMAGE"]),
    Case("quạt điện quạt kêu và rung", "diagnose", "electric_fan", ["FAN_WOBBLE"]),
    Case("đường ống nước gạch bị bong", "diagnose", "water_pipe", ["PIPE_JOINT_LEAK"]),
    Case("ấm đun nước đèn không sáng", "diagnose", "kettle", ["KETTLE_SWITCH"]),
    Case("quạt trần chiết áp hỏng", "diagnose", "ceiling_fan", ["CEILFAN_SPEED_SWITCH"]),
    Case("khoa van tay keu tit tit", "diagnose", "smart_lock", ["LOCK_LOW_BATTERY"]),
    Case("chuyển nhà xong tivi bị vệt", "diagnose", "television", ["TV_PANEL_DAMAGE"]),
    Case("ấm đun nước ấm cứ tắt sớm", "diagnose", "kettle", ["KETTLE_THERMOSTAT"]),
    Case("lò nướng chỉ có thanh trên đỏ", "diagnose", "oven", ["OVEN_HEATING_ELEMENT"]),
    Case("máy sấy chạy mà lồng đứng yên", "diagnose", "clothes_dryer", ["DRYER_NOT_SPINNING"]),
    Case("vòi nước lõi vòi hỏng", "diagnose", "faucet", ["FAUCET_CARTRIDGE"]),
    Case("máy lạnh chảy", "diagnose", "air_conditioner", ["AC_SMELL_BURNT"]),
    Case("bep tu bao loi e1", "diagnose", "induction_hob", ["HOB_ERROR_CODE"]),
    Case("quạt điện quay tay thấy nặng", "diagnose", "electric_fan", ["FAN_WORN_BEARING"]),
    Case("lò nướng bánh cháy mặt sống ruột", "diagnose", "oven", ["OVEN_HEATING_ELEMENT"]),
    Case("bồn rửa cái lưới thoát bị mục", "diagnose", "sink", ["SINK_DRAIN_CORRODED"]),
    Case("tủ lạnh hết khí lạnh", "diagnose", "refrigerator", ["FRIDGE_LOW_GAS"]),
    Case("bồn cầu nhà em khóc suốt", "diagnose", "toilet", ["TOILET_FLAPPER_LEAK"]),
    Case("đường ống nước nước có cặn", "diagnose", "water_pipe", ["PIPE_RUSTY_WATER"]),
    Case("lò vi sóng lò ồn tới mức nói chuyện không nghe", "diagnose", "microwave_oven", ["MW_FAN_NOISY"]),
    Case("may loc nuoc", "diagnose", "air_conditioner", ["AC_DRAIN_BLOCKED"]),
    Case("quạt điện dây quạt bị đứt", "diagnose", "electric_fan", ["FAN_CORD_DAMAGE"]),
    Case("lò vi sóng phải đè cửa mới chạy", "diagnose", "microwave_oven", ["MW_DOOR_SWITCH"]),
    Case("lò nướng không ăn thua", "diagnose", "oven", ["OVEN_HEATING_ELEMENT"]),
    Case("quạt trần kêu ù ù", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("máy lọc nước chạy liên tục không nghỉ", "diagnose", "water_purifier", ["PURIFIER_PUMP_RUNS_ON"]),
    Case("ổ cắm điện cắm vào xẹt lửa", "diagnose", "power_outlet", ["OUTLET_SHORT_CIRCUIT"]),
    Case("lò vi sóng phải đẩy cửa một kiểu nó mới ăn", "diagnose", "microwave_oven", ["MW_DOOR_SWITCH"]),
    Case("cây nước nóng lạnh không vào điện", "diagnose", "water_purifier", ["PURIFIER_NO_POWER"]),
    Case("xả máy giặt là nước trào lên bồn rửa", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("bồn cầu tắc cống", "diagnose", "toilet", ["TOILET_CLOGGED"]),
    Case("bếp từ kêu rít nghe khó chịu", "diagnose", "induction_hob", ["HOB_FAN_NOISY"]),
    Case("vòi nước đáy tủ bị phồng", "diagnose", "faucet", ["FAUCET_BASE_LEAK"]),
    Case("máy nước nóng phải nhấn nút mới chạy lại", "diagnose", "water_heater", ["WH_THERMOSTAT"]),
    Case("bồn cầu bệ ngồi bị nứt", "diagnose", "toilet", ["TOILET_SEAT_BROKEN"]),
    Case("máy giặt vào được một ít rồi dừng", "diagnose", "washing_machine", ["WM_NO_WATER_INLET"]),
    Case("bồn rửa nước không chịu xuống", "diagnose", "sink", ["SINK_CLOGGED"]),
    Case("quạt trần xoay số không ăn", "diagnose", "ceiling_fan", ["CEILFAN_SPEED_SWITCH"]),
    Case("bóng đèn đèn không sáng như trước", "diagnose", "light_bulb", ["LIGHT_DIM"]),
    Case("khóa cửa thông minh khóa cửa nháy đèn đỏ liên tục", "diagnose", "smart_lock", ["LOCK_LOW_BATTERY"]),
    Case("lò vi sóng ồn hơn trước", "diagnose", "microwave_oven", ["MW_FAN_NOISY"]),
    Case("bếp từ thổi hơi nóng ra rất mạnh", "diagnose", "induction_hob", ["HOB_FAN_NOISY"]),
    Case("máy rửa bát kêu ù ù rồi dừng", "diagnose", "dishwasher", ["DW_NO_WATER"]),
    Case("quạt điện cái nút nó lì lắm", "diagnose", "electric_fan", ["FAN_SWITCH_FAULT"]),
    Case("bồn rửa bẫy nước bị chảy", "diagnose", "sink", ["SINK_TRAP_LEAK"]),
    Case("đường ống nước nước yếu dần", "diagnose", "water_pipe", ["PIPE_LOW_PRESSURE"]),
    Case("vòi nước vòi gạt bị rít", "diagnose", "faucet", ["FAUCET_CARTRIDGE"]),
    Case("lò nướng cái núm vặn giờ nó không ăn", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("khoá vân tay kêu tít tít mỗi lần mở", "diagnose", "smart_lock", ["LOCK_LOW_BATTERY"]),
    Case("lò vi sóng nấu xong lò vẫn kêu mãi", "diagnose", "microwave_oven", ["MW_FAN_NOISY"]),
    Case("may rua bat chet nguon", "diagnose", "dishwasher", ["DW_NO_POWER"]),
    Case("bồn cầu két nó kêu rít rít", "diagnose", "toilet", ["TOILET_FILL_VALVE"]),
    Case("quạt điện cái nút đảo bấm không ăn", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("đường ống nước vòi kêu rít", "diagnose", "water_pipe", ["PIPE_NOISY"]),
    Case("ấm siêu tốc không đun được", "diagnose", "kettle", ["KETTLE_HEATING_BASE"]),
    Case("ổ cắm điện cắm vào không chặt", "diagnose", "power_outlet", ["OUTLET_LOOSE_CONTACT"]),
    Case("lò vi sóng lò nóng vỏ", "diagnose", "microwave_oven", ["MW_FAN_NOISY"]),
    Case("bếp gas lâu sôi lắm", "diagnose", "gas_stove", ["STOVE_BURNER_CLOGGED"]),
    Case("bếp gas phải đè tay xuống", "diagnose", "gas_stove", ["STOVE_FLAME_OUT"]),
    Case("lò vi sóng mất tác dụng", "diagnose", "microwave_oven", ["MW_MAGNETRON"]),
    Case("máy giặt phải đẩy rất mạnh mới đóng ăn", "diagnose", "washing_machine", ["WM_DOOR_LOCK"]),
    Case("bóng đèn ngồi dưới đèn đó bị nhức đầu", "diagnose", "light_bulb", ["LIGHT_FLICKERING"]),
    Case("tivi màn hình bị vỡ", "diagnose", "television", ["TV_PANEL_DAMAGE"]),
    Case("máy nước nóng bình không ra nước", "diagnose", "water_heater", ["WH_LOW_PRESSURE"]),
    Case("quạt điện cục pin quạt", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("khóa cửa thông minh khoá nhận vân rồi mà cửa vẫn không bật ra", "diagnose", "smart_lock", ["LOCK_MOTOR_FAULT"]),
    Case("máy sấy quần áo máy sấy bật lên không thấy gì chạy", "diagnose", "clothes_dryer", ["DRYER_NOT_SPINNING"]),
    Case("tivi tắt ngúm", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("ổ cắm lỏng khỏi tường", "diagnose", "power_outlet", ["OUTLET_BROKEN_FACE"]),
    Case("đường ống nước nhà em bị thấm không biết ở đâu", "diagnose", "water_pipe", ["PIPE_JOINT_LEAK"]),
    Case("ống nước bị nghẹt", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("quạt điện quạt nhà em khét lắm", "diagnose", "electric_fan", ["FAN_MOTOR_BURNT"]),
    Case("nhựa ổ cắm chảy ra", "diagnose", "power_outlet", ["OUTLET_SHORT_CIRCUIT"]),
    Case("khóa cửa thông minh khoá hết pin mà em đang ở ngoài", "diagnose", "smart_lock", ["LOCK_LOCKED_OUT"]),
    Case("bóng đèn công tắc lỏng", "diagnose", "light_bulb", ["LIGHT_SWITCH_FAULT"]),
    Case("máy lạnh mô tơ ngoài không chạy", "diagnose", "air_conditioner", ["AC_CAPACITOR"]),
    Case("bếp gas lửa như đèn dầu", "diagnose", "gas_stove", ["STOVE_BURNER_CLOGGED"]),
    Case("đường ống nước nước tuôn không ngừng", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("may say chet nguon", "diagnose", "clothes_dryer", ["DRYER_NO_POWER"]),
    Case("quạt điện quạt nhà em kén số", "diagnose", "electric_fan", ["FAN_SWITCH_FAULT"]),
    Case("cục pin trong cục nóng hỏng", "diagnose", "air_conditioner", ["AC_CAPACITOR"]),
    Case("bếp từ bếp không ăn nồi", "diagnose", "induction_hob", ["HOB_NO_PAN_DETECT"]),
    Case("máy lọc nước nuoc loc uong nhat", "diagnose", "water_purifier", ["PURIFIER_FILTER_DUE"]),
    Case("máy lọc nước kêu to hơn trước nhiều", "diagnose", "water_purifier", ["PURIFIER_PUMP_RUNS_ON"]),
    Case("quạt điện quạt phải lấy tay quay mới chạy", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("máy rửa chén báo lỗi cấp nước", "diagnose", "dishwasher", ["DW_NO_WATER"]),
    Case("vòi nước khoá rồi mà vẫn chảy", "diagnose", "faucet", ["FAUCET_DRIP"]),
    Case("lò vi sóng màn hình lò không sáng", "diagnose", "microwave_oven", ["MW_NO_POWER"]),
    Case("ổ cắm không có điện", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("tivi không dò được kênh", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("lò nướng cửa lò không đóng kín", "diagnose", "oven", ["OVEN_DOOR_GLASS"]),
    Case("bếp gas lửa không đều", "diagnose", "gas_stove", ["STOVE_BURNER_CLOGGED"]),
    Case("bồn cầu xả xong lâu lắm mới xả lại được", "diagnose", "toilet", ["TOILET_FILL_VALVE"]),
    Case("vòi nước đáy tủ bị mủn ra", "diagnose", "faucet", ["FAUCET_BASE_LEAK"]),
    Case("ấm siêu tốc rò điện", "diagnose", "kettle", ["KETTLE_LEAK"]),
    Case("bếp từ bếp này dùng được hai năm là hỏng đúng không em", "diagnose", "induction_hob", ["HOB_NO_PAN_DETECT"]),
    Case("máy sấy quần áo lồng không quay", "diagnose", "clothes_dryer", ["DRYER_NOT_SPINNING"]),
    Case("ổ cắm bốc khói", "diagnose", "power_outlet", ["OUTLET_SHORT_CIRCUIT"]),
    Case("tivi app không chạy", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("bóng đèn sáng không đủ đọc sách", "diagnose", "light_bulb", ["LIGHT_DIM"]),
    Case("bóng đèn đèn có mùi khét", "diagnose", "light_bulb", ["LIGHT_FIXTURE_LEAK"]),
    Case("tivi không nhận điều khiển", "diagnose", "television", ["TV_REMOTE_FAULT"]),
    Case("tivi màn hình bị chảy mực", "diagnose", "television", ["TV_PANEL_DAMAGE"]),
    Case("dưới bồn rửa bị rò nước", "diagnose", "sink", ["SINK_TRAP_LEAK"]),
    Case("tivi góc màn hình bị tối", "diagnose", "television", ["TV_BACKLIGHT"]),
    Case("quạt điện quạt chỉ thổi một hướng", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("máy giặt cái bọc cửa bị rách", "diagnose", "washing_machine", ["WM_DOOR_SEAL_LEAK"]),
    Case("bep tu cam dien khong len", "diagnose", "induction_hob", ["HOB_NO_POWER"]),
    Case("vòi sen yếu quá", "diagnose", "water_pipe", ["PIPE_LOW_PRESSURE"]),
    Case("quạt trần có mùi cháy trong phòng mà không biết ở đâu", "diagnose", "ceiling_fan", ["CEILFAN_MOTOR_BURNT"]),
    Case("lò vi sóng mâm xoay bị vỡ", "diagnose", "microwave_oven", ["MW_TURNTABLE_MOTOR"]),
    Case("quạt điện quạt ù ù mà không chạy", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("bồn cầu nghẹt bàn cầu", "diagnose", "toilet", ["TOILET_CLOGGED"]),
    Case("may rua bat sang den roi tat", "diagnose", "dishwasher", ["DW_NO_POWER"]),
    Case("nước nhỏ giọt ở máy lọc", "diagnose", "water_purifier", ["PURIFIER_LEAK"]),
    Case("ổ cắm điện cắm vào lỏng lẻo", "diagnose", "power_outlet", ["OUTLET_LOOSE_CONTACT"]),
    Case("lò vi sóng bị cháy trong ruột", "diagnose", "microwave_oven", ["MW_SPARKING"]),
    Case("ấm đun nước ấm chạy mà không nóng", "diagnose", "kettle", ["KETTLE_HEATING_BASE"]),
    Case("ống nước nhỏ giọt", "diagnose", "water_pipe", ["PIPE_JOINT_LEAK"]),
    Case("bóng đèn bấm công tắc không lên đèn", "diagnose", "light_bulb", ["LIGHT_SWITCH_FAULT"]),
    Case("lò nướng cửa lò nóng quá", "diagnose", "oven", ["OVEN_DOOR_GLASS"]),
    Case("ổ cắm điện aptomat nhảy liên tục", "diagnose", "power_outlet", ["OUTLET_TRIPS_BREAKER"]),
    Case("ổ cắm không ra điện", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("hôm qua sét đánh xong tivi không lên", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("quạt trần khét lẹt", "diagnose", "ceiling_fan", ["CEILFAN_MOTOR_BURNT"]),
    Case("mat kinh bep tu bi nut", "diagnose", "induction_hob", ["HOB_GLASS_CRACKED"]),
    Case("kính lò nướng bị rạn", "diagnose", "oven", ["OVEN_DOOR_GLASS"]),
    Case("quạt trần chắc quạt cũ quá rồi hả em", "diagnose", "ceiling_fan", ["CEILFAN_CAPACITOR"]),
    Case("quạt điện quạt khô dầu", "diagnose", "electric_fan", ["FAN_WORN_BEARING"]),
    Case("bếp gas tạch mà không cháy", "diagnose", "gas_stove", ["STOVE_IGNITER"]),
    Case("lò vi sóng lò chết hẳn", "diagnose", "microwave_oven", ["MW_NO_POWER"]),
    Case("bếp gas lắp van vào bị xì", "diagnose", "gas_stove", ["STOVE_REGULATOR"]),
    Case("lò vi sóng bật lò là nhảy aptomat", "diagnose", "microwave_oven", ["MW_NO_POWER"]),
    Case("quạt trần kêu cót két", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("bếp gas núm quay tự do", "diagnose", "gas_stove", ["STOVE_VALVE_STUCK"]),
    Case("may say quay ma khong nong", "diagnose", "clothes_dryer", ["DRYER_NOT_HEATING"]),
    Case("bếp từ không tắt được", "diagnose", "induction_hob", ["HOB_TOUCH_FAULT"]),
    Case("quạt trần ù mà không quay", "diagnose", "ceiling_fan", ["CEILFAN_MOTOR_BURNT"]),
    Case("khóa cửa thông minh quên mật khẩu khoá cửa rồi", "diagnose", "smart_lock", ["LOCK_LOCKED_OUT"]),
    Case("quạt trần nằm dưới mà không dám ngủ", "diagnose", "ceiling_fan", ["CEILFAN_MOUNT_LOOSE"]),
    Case("bếp gas bếp cháy một lúc rồi tắt", "diagnose", "gas_stove", ["STOVE_FLAME_OUT"]),
    Case("khóa cửa thông minh đồ ăn em để ngoài cửa nãy giờ", "diagnose", "smart_lock", ["LOCK_LOCKED_OUT"]),
    Case("đường ống nước nước phun như vòi rồng", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("lò vi sóng mâm không quay", "diagnose", "microwave_oven", ["MW_TURNTABLE_MOTOR"]),
    Case("bếp gas hai bếp đều yếu", "diagnose", "gas_stove", ["STOVE_REGULATOR"]),
    Case("cắm máy rửa bát vào là nhảy aptomat", "diagnose", "dishwasher", ["DW_NO_POWER"]),
    Case("quạt điện quạt kêu è è không quay", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("hôi mùi gas", "diagnose", "gas_stove", ["STOVE_GAS_LEAK"]),
    Case("lò nướng lò nhà em nóng quá tay", "diagnose", "oven", ["OVEN_THERMOSTAT"]),
    Case("máy nước nóng may so hỏng", "diagnose", "water_heater", ["WH_HEATING_ELEMENT"]),
    Case("khóa cửa thông minh dat tay mai khoa khong mo", "diagnose", "smart_lock", ["LOCK_FINGERPRINT_FAIL"]),
    Case("máy rửa bát bát ra khô cong mà vẫn bẩn", "diagnose", "dishwasher", ["DW_NO_WATER"]),
    Case("tivi bị đơ", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("bồn cầu phải giữ nút mới xả được", "diagnose", "toilet", ["TOILET_WEAK_FLUSH"]),
    Case("tủ lạnh kêu như máy cày", "diagnose", "refrigerator", ["FRIDGE_NOISY"]),
    Case("lò vi sóng không vào điện", "diagnose", "microwave_oven", ["MW_NO_POWER"]),
    Case("lò vi sóng đĩa đứng im", "diagnose", "microwave_oven", ["MW_TURNTABLE_MOTOR"]),
    Case("quạt điện quạt đảo giật cục", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("máy sấy quần áo máy chạy mà quần áo không xoay tí nào", "diagnose", "clothes_dryer", ["DRYER_NOT_SPINNING"]),
    Case("quạt điện quạt không tuốc năng", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("lò vi sóng bốc lửa", "diagnose", "microwave_oven", ["MW_SPARKING"]),
    Case("quạt điện quạt chạy ì ạch", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("bếp gas bình này chắc bị bơm thiếu", "diagnose", "gas_stove", ["STOVE_REGULATOR"]),
    Case("bếp gas bình còn gas mà lửa nhỏ", "diagnose", "gas_stove", ["STOVE_REGULATOR"]),
    Case("ổ cắm rơ", "diagnose", "power_outlet", ["OUTLET_LOOSE_CONTACT"]),
    Case("khóa cửa thông minh em đang đứng ngoài cửa không vào nhà được", "diagnose", "smart_lock", ["LOCK_LOCKED_OUT"]),
    Case("tivi rì mốt hỏng", "diagnose", "television", ["TV_REMOTE_FAULT"]),
    Case("tivi bị lag", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("tivi mờ đi", "diagnose", "television", ["TV_BACKLIGHT"]),
    Case("máy rửa bát sáng đèn rồi tắt ngay", "diagnose", "dishwasher", ["DW_NO_POWER"]),
    Case("may rua chen khong rut nuoc", "diagnose", "dishwasher", ["DW_NOT_DRAINING"]),
    Case("may rua chen cam dien khong chay", "diagnose", "dishwasher", ["DW_NO_POWER"]),
    Case("phải đẩy phích lên mới chạy", "diagnose", "power_outlet", ["OUTLET_LOOSE_CONTACT"]),
    Case("quạt trần kêu nhức đầu", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("vòi rửa mặt yếu", "diagnose", "faucet", ["FAUCET_LOW_FLOW"]),
    Case("tivi màn hình bị đốm đen", "diagnose", "television", ["TV_PANEL_DAMAGE"]),
    Case("máy giặt chảy nước ra sàn", "diagnose", "washing_machine", ["WM_OVERFLOW"]),
    Case("lò vi sóng cái lẫy cửa gãy rồi", "diagnose", "microwave_oven", ["MW_DOOR_SWITCH"]),
    Case("ấm đun nước phải xoay ấm mới chạy", "diagnose", "kettle", ["KETTLE_SWITCH"]),
    Case("may say keu to", "diagnose", "clothes_dryer", ["DRYER_NOISY"]),
    Case("máy lọc nước nước lọc chảy yếu dần mấy hôm nay", "diagnose", "water_purifier", ["PURIFIER_NO_WATER"]),
    Case("quạt trần rung", "diagnose", "ceiling_fan", ["CEILFAN_MOUNT_LOOSE"]),
    Case("máy lọc nước voi loc khong co nuoc", "diagnose", "water_purifier", ["PURIFIER_NO_WATER"]),
    Case("bếp gas buông tay ra là tắt", "diagnose", "gas_stove", ["STOVE_FLAME_OUT"]),
    Case("quạt trần nhìn nó lung lay sợ quá", "diagnose", "ceiling_fan", ["CEILFAN_MOUNT_LOOSE"]),
    Case("bep tu khong vao dien", "diagnose", "induction_hob", ["HOB_NO_POWER"]),
    Case("bếp gas mùi ga nồng lắm", "diagnose", "gas_stove", ["STOVE_GAS_LEAK"]),
    Case("vòi nước vòi không ngừng được", "diagnose", "faucet", ["FAUCET_DRIP"]),
    Case("vòi nước dây cấp nước bị rỉ", "diagnose", "faucet", ["FAUCET_BASE_LEAK"]),
    Case("lò vi sóng lò chạy mà đồ ăn không nóng", "diagnose", "microwave_oven", ["MW_MAGNETRON"]),
    Case("cúp điện xong tivi hỏng luôn", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("quạt điện quạt nóng rát tay", "diagnose", "electric_fan", ["FAN_MOTOR_BURNT"]),
    Case("bep tu khong tat duoc", "diagnose", "induction_hob", ["HOB_TOUCH_FAULT"]),
    Case("vòi nước nước ra nhỏ", "diagnose", "faucet", ["FAUCET_LOW_FLOW"]),
    Case("bếp từ bep tat roi ma van keu", "diagnose", "induction_hob", ["HOB_FAN_NOISY"]),
    Case("lò nướng phím lò không ăn", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("quạt điện chạm vào quạt thấy tê", "diagnose", "electric_fan", ["FAN_CORD_DAMAGE"]),
    Case("đường ống nước nước chảy ào ào", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("ống nước rung", "diagnose", "water_pipe", ["PIPE_NOISY"]),
    Case("quạt trần rung như sắp rơi", "diagnose", "ceiling_fan", ["CEILFAN_MOUNT_LOOSE"]),
    Case("vòi nước nước chảy như nước mắt", "diagnose", "faucet", ["FAUCET_LOW_FLOW"]),
    Case("máy lọc nước chắc phải thay cả máy mới", "diagnose", "water_purifier", ["PURIFIER_FILTER_DUE"]),
    Case("bếp gas bếp ăn gas mà không nóng", "diagnose", "gas_stove", ["STOVE_BURNER_CLOGGED"]),
    Case("máy lọc nước tự nhiên ngừng hoạt động", "diagnose", "water_purifier", ["PURIFIER_NO_POWER"]),
    Case("máy lọc nước may loc cach cach lien tuc", "diagnose", "water_purifier", ["PURIFIER_PUMP_RUNS_ON"]),
    Case("vỡ ống nước", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("tivi tiếng bị méo", "diagnose", "television", ["TV_NO_SOUND"]),
    Case("mặt bếp từ rạn chân chim một đường", "diagnose", "induction_hob", ["HOB_GLASS_CRACKED"]),
    Case("máy lọc nước nước lọc dạo này uống nhạt hơn trước", "diagnose", "water_purifier", ["PURIFIER_FILTER_DUE"]),
    Case("bếp gas vặn nhỏ là tắt", "diagnose", "gas_stove", ["STOVE_FLAME_OUT"]),
    Case("hộp số quạt trần hỏng", "diagnose", "ceiling_fan", ["CEILFAN_SPEED_SWITCH"]),
    Case("máy giặt rút điện rồi nước vẫn vào", "diagnose", "washing_machine", ["WM_OVERFLOW"]),
    Case("quạt trần chạy chậm dần", "diagnose", "ceiling_fan", ["CEILFAN_CAPACITOR"]),
    Case("máy sấy dạo này lâu khô hơn hẳn", "diagnose", "clothes_dryer", ["DRYER_LINT_CLOGGED"]),
    Case("bếp từ bếp nhận nồi này mà không nhận nồi kia", "diagnose", "induction_hob", ["HOB_NO_PAN_DETECT"]),
    Case("khóa cửa thông minh mất thẻ từ không mở được cửa", "diagnose", "smart_lock", ["LOCK_LOCKED_OUT"]),
    Case("tivi có hình mà không có tiếng", "diagnose", "television", ["TV_NO_SOUND"]),
    Case("bồn cầu nước vào chậm", "diagnose", "toilet", ["TOILET_FILL_VALVE"]),
    Case("khóa cửa thông minh khoá thông minh tự nhiên sập nguồn", "diagnose", "smart_lock", ["LOCK_LOW_BATTERY"]),
    Case("quạt trần nghiêng", "diagnose", "ceiling_fan", ["CEILFAN_MOUNT_LOOSE"]),
    Case("bồn cầu chảy nước liên tục", "diagnose", "toilet", ["TOILET_FLAPPER_LEAK"]),
    Case("bếp từ chắc phải thay cả bếp mới đúng không em", "diagnose", "induction_hob", ["HOB_GLASS_CRACKED"]),
    Case("máy rửa bát máy chạy mà không thấy nước vào", "diagnose", "dishwasher", ["DW_NO_WATER"]),
    Case("máy rửa bát chạy xong vẫn còn nước bên trong", "diagnose", "dishwasher", ["DW_NOT_DRAINING"]),
    Case("bóng đèn đèn âm trần chảy nước", "diagnose", "light_bulb", ["LIGHT_FIXTURE_LEAK"]),
    Case("ấm đun nước ấm không hoạt động", "diagnose", "kettle", ["KETTLE_HEATING_BASE"]),
    Case("bếp từ hiện chữ E rồi tắt", "diagnose", "induction_hob", ["HOB_ERROR_CODE"]),
    Case("bồn rửa ống cong dưới bồn bị nứt", "diagnose", "sink", ["SINK_TRAP_LEAK"]),
    Case("khóa vân tay nhà em không nhận vân nữa", "diagnose", "smart_lock", ["LOCK_FINGERPRINT_FAIL"]),
    Case("lò không có điện", "diagnose", "microwave_oven", ["MW_NO_POWER"]),
    Case("bếp gas lửa không xanh", "diagnose", "gas_stove", ["STOVE_BURNER_CLOGGED"]),
    Case("lò vi sóng cửa lò lỏng lẻo", "diagnose", "microwave_oven", ["MW_DOOR_SWITCH"]),
    Case("lò nướng màn hình lò nhấp nháy", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("đường ống nước nước thoát chậm", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("tivi vết mực trên màn hình", "diagnose", "television", ["TV_PANEL_DAMAGE"]),
    Case("bồn cầu xả hoài không xuống", "diagnose", "toilet", ["TOILET_CLOGGED"]),
    Case("ổ cắm điện cắm vào nghe cái bụp", "diagnose", "power_outlet", ["OUTLET_SHORT_CIRCUIT"]),
    Case("quạt trần lắc lư", "diagnose", "ceiling_fan", ["CEILFAN_MOUNT_LOOSE"]),
    Case("tivi im re mà hình vẫn chạy", "diagnose", "television", ["TV_NO_SOUND"]),
    Case("máy nước nóng chỗ này được chỗ kia không", "diagnose", "water_heater", ["WH_LOW_PRESSURE"]),
    Case("máy lọc nước lâu rồi em chưa thay lõi có sao không", "diagnose", "water_purifier", ["PURIFIER_FILTER_DUE"]),
    Case("đường ống nước nước dâng ngược lên", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("máy sấy quần áo tiền điện tăng mà áo vẫn không khô", "diagnose", "clothes_dryer", ["DRYER_NOT_HEATING"]),
    Case("bồn rửa mùi cống bốc lên", "diagnose", "sink", ["SINK_SMELL"]),
    Case("chỉnh nước nóng mà ra nước lạnh", "diagnose", "faucet", ["FAUCET_CARTRIDGE"]),
    Case("khóa cửa thông minh chốt khoá cửa không rút vào", "diagnose", "smart_lock", ["LOCK_MOTOR_FAULT"]),
    Case("bếp gas bếp không giữ được lửa", "diagnose", "gas_stove", ["STOVE_FLAME_OUT"]),
    Case("dây curoa máy sấy đứt", "diagnose", "clothes_dryer", ["DRYER_NOT_SPINNING"]),
    Case("máy nước nóng máy không ăn", "diagnose", "water_heater", ["WH_INSTANT_NO_HOT"]),
    Case("lò nướng nướng hai khay thì khay dưới không chín", "diagnose", "oven", ["OVEN_FAN_FAULT"]),
    Case("bồn cầu nhà tắm hôi mà không biết ở đâu", "diagnose", "toilet", ["TOILET_BASE_LEAK"]),
    Case("máy sấy quần áo hàng xóm phàn nàn vì máy kêu", "diagnose", "clothes_dryer", ["DRYER_NOISY"]),
    Case("đường ống nước áp lực nước yếu", "diagnose", "water_pipe", ["PIPE_LOW_PRESSURE"]),
    Case("lò nướng quạt trong lò kêu rít", "diagnose", "oven", ["OVEN_FAN_FAULT"]),
    Case("quạt điện quạt chỉ chạy số 3", "diagnose", "electric_fan", ["FAN_SWITCH_FAULT"]),
    Case("máy rửa bát bấm không phản hồi", "diagnose", "dishwasher", ["DW_NO_POWER"]),
    Case("tivi chết hẳn", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("ổ cắm nhà em nó rơi ra", "diagnose", "power_outlet", ["OUTLET_BROKEN_FACE"]),
    Case("quạt trần sợ quạt rơi", "diagnose", "ceiling_fan", ["CEILFAN_MOUNT_LOOSE"]),
    Case("máy sấy có mùi khét", "diagnose", "clothes_dryer", ["DRYER_LINT_CLOGGED"]),
    Case("đường ống nước nước lên ngược", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("máy lọc nước nước lọc có cặn trắng ở đáy bình", "diagnose", "water_purifier", ["PURIFIER_FILTER_DUE"]),
    Case("bóng đèn đèn chớp nháy", "diagnose", "light_bulb", ["LIGHT_FLICKERING"]),
    Case("den tu lanh chay", "diagnose", "refrigerator", ["FRIDGE_LIGHT_FAULT"]),
    Case("quạt trần chỉ chạy một tốc độ", "diagnose", "ceiling_fan", ["CEILFAN_SPEED_SWITCH"]),
    Case("lò nướng lò không đúng nhiệt độ", "diagnose", "oven", ["OVEN_THERMOSTAT"]),
    Case("quạt trần nghe như cối xay", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("bếp từ bếp cảm ứng dùng vài năm là đơ đúng không em", "diagnose", "induction_hob", ["HOB_TOUCH_FAULT"]),
    Case("tivi màn hình không sáng", "diagnose", "television", ["TV_BACKLIGHT"]),
    Case("tivi cái điều khiển chết rồi", "diagnose", "television", ["TV_REMOTE_FAULT"]),
    Case("đường ống nước nước đọng hoài không rút", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("ổ cắm nóng quá", "diagnose", "power_outlet", ["OUTLET_OVERLOAD"]),
    Case("quạt đứng im một chỗ", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("quạt trần có mùi khét", "diagnose", "ceiling_fan", ["CEILFAN_MOTOR_BURNT"]),
    Case("bếp từ nóng máy rồi tự tắt", "diagnose", "induction_hob", ["HOB_FAN_NOISY"]),
    Case("bóng đèn đèn bị vào nước", "diagnose", "light_bulb", ["LIGHT_FIXTURE_LEAK"]),
    Case("bóng đèn nước nhỏ từ đèn xuống", "diagnose", "light_bulb", ["LIGHT_FIXTURE_LEAK"]),
    Case("ổ cắm điện cả phòng mất điện", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("vòi nước chân vòi bị rò", "diagnose", "faucet", ["FAUCET_BASE_LEAK"]),
    Case("ổ cắm hơi ấm", "diagnose", "power_outlet", ["OUTLET_LOOSE_CONTACT"]),
    Case("may rua bat tran nuoc ra san", "diagnose", "dishwasher", ["DW_NOT_DRAINING"]),
    Case("máy lọc nước bom may loc khong ngat", "diagnose", "water_purifier", ["PURIFIER_PUMP_RUNS_ON"]),
    Case("bồn cầu nước tràn trong két", "diagnose", "toilet", ["TOILET_FILL_VALVE"]),
    Case("bếp từ tối thui không sáng đèn gì cả", "diagnose", "induction_hob", ["HOB_NO_POWER"]),
    Case("ấm đun nước cái đế nó chập chờn", "diagnose", "kettle", ["KETTLE_SWITCH"]),
    Case("ấm đun nước ấm nhà em phải ấn mạnh mới chạy", "diagnose", "kettle", ["KETTLE_SWITCH"]),
    Case("bồn rửa rửa bát xong thấy nước dưới gầm", "diagnose", "sink", ["SINK_TRAP_LEAK"]),
    Case("ổ cắm điện gạt lên được một lúc lại xuống", "diagnose", "power_outlet", ["OUTLET_TRIPS_BREAKER"]),
    Case("tủ dưới bồn rửa có mùi", "diagnose", "faucet", ["FAUCET_BASE_LEAK"]),
    Case("lò nướng lò không tự tắt", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("bóng đèn đèn nhấp nháy", "diagnose", "light_bulb", ["LIGHT_FLICKERING"]),
    Case("công tắc đèn hỏng", "diagnose", "light_bulb", ["LIGHT_SWITCH_FAULT"]),
    Case("bồn rửa cái lọc rác bị rỉ", "diagnose", "sink", ["SINK_DRAIN_CORRODED"]),
    Case("bếp gas bếp lửa yếu", "diagnose", "gas_stove", ["STOVE_BURNER_CLOGGED"]),
    Case("máy lọc nước bơm chạy suốt không nghỉ", "diagnose", "water_purifier", ["PURIFIER_PUMP_RUNS_ON"]),
    Case("tivi chỉ có tiếng một bên", "diagnose", "television", ["TV_NO_SOUND"]),
    Case("máy lọc nước nhà em quay lại mua nước bình rồi", "diagnose", "water_purifier", ["PURIFIER_NO_WATER"]),
    Case("lavabo bị tắc", "diagnose", "sink", ["SINK_CLOGGED"]),
    Case("đường ống nước nước có mùi lạ", "diagnose", "water_pipe", ["PIPE_RUSTY_WATER"]),
    Case("tủ lạnh cửa không hít", "diagnose", "refrigerator", ["FRIDGE_DOOR_GASKET"]),
    Case("lò nướng bấm nút không được", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("quạt điện quạt hết hơi rồi", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("vòi nước cái cần vòi nó cứng ngắc", "diagnose", "faucet", ["FAUCET_CARTRIDGE"]),
    Case("đường ống nước tường bị mốc", "diagnose", "water_pipe", ["PIPE_JOINT_LEAK"]),
    Case("quạt điện mùi khê khê", "diagnose", "electric_fan", ["FAN_MOTOR_BURNT"]),
    Case("bếp gas con xoay bếp không nhúc nhích", "diagnose", "gas_stove", ["STOVE_VALVE_STUCK"]),
    Case("tivi bấm remote không nhận", "diagnose", "television", ["TV_REMOTE_FAULT"]),
    Case("máy rửa bát chân tủ bếp bị phồng lên", "diagnose", "dishwasher", ["DW_DOOR_LEAK"]),
    Case("ổ cắm không lên", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("quạt điện quạt nhà em bị liệt cổ", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("bếp từ nhà em vỡ mặt kính rồi", "diagnose", "induction_hob", ["HOB_GLASS_CRACKED"]),
    Case("tivi chỉ có nút nguồn không ăn", "diagnose", "television", ["TV_REMOTE_FAULT"]),
    Case("lò nướng vặn núm mà lò không lên", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("quạt điện cánh quạt đảo", "diagnose", "electric_fan", ["FAN_WOBBLE"]),
    Case("lò nướng timer lò hỏng", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("tivi tự tắt liên tục", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("khoa van tay luc duoc luc khong", "diagnose", "smart_lock", ["LOCK_FINGERPRINT_FAIL"]),
    Case("bóng đèn đèn hỏng rồi", "diagnose", "light_bulb", ["LIGHT_BULB_DEAD"]),
    Case("ấm đun nước ấm nhà em bị ố đáy", "diagnose", "kettle", ["KETTLE_SCALE"]),
    Case("quạt trần chạy nặng", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("tủ lạnh vẫn lạnh bình thường", "diagnose", "refrigerator", ["FRIDGE_NOISY"]),
    Case("đường ống nước tường kêu khi mở nước", "diagnose", "water_pipe", ["PIPE_NOISY"]),
    Case("quạt điện bật lên không nhúc nhích", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("máy rửa bát máy này rẻ tiền nên rửa không sạch", "diagnose", "dishwasher", ["DW_NOT_CLEAN"]),
    Case("ấm đun nước cắm vào không thấy gì", "diagnose", "kettle", ["KETTLE_HEATING_BASE"]),
    Case("quạt điện gạt dây là tắt", "diagnose", "electric_fan", ["FAN_CORD_DAMAGE"]),
    Case("quạt điện quạt như sắp rớt", "diagnose", "electric_fan", ["FAN_WOBBLE"]),
    Case("lò nướng kính lò bị vỡ một góc", "diagnose", "oven", ["OVEN_DOOR_GLASS"]),
    Case("vòi nước chảy yếu", "diagnose", "faucet", ["FAUCET_LOW_FLOW"]),
    Case("bóng đèn phòng cứ âm u", "diagnose", "light_bulb", ["LIGHT_DIM"]),
    Case("ấm đun nước gạt công tắc không giữ", "diagnose", "kettle", ["KETTLE_THERMOSTAT"]),
    Case("máy sấy sáng đèn mà không chạy", "diagnose", "clothes_dryer", ["DRYER_NO_POWER"]),
    Case("tivi đèn báo nhấp nháy mà không lên", "diagnose", "television", ["TV_POWER_BOARD"]),
    Case("đường ống nước nghe cốp một cái khi đóng vòi", "diagnose", "water_pipe", ["PIPE_NOISY"]),
    Case("khóa cửa thông minh từ hôm trời nồm là khoá khó nhận vân", "diagnose", "smart_lock", ["LOCK_FINGERPRINT_FAIL"]),
    Case("tivi không vào được mạng", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("tủ lạnh hư mô tơ", "diagnose", "refrigerator", ["FRIDGE_COMPRESSOR"]),
    Case("bếp gas không tắt được bếp", "diagnose", "gas_stove", ["STOVE_VALVE_STUCK"]),
    Case("tivi điều khiển đơ", "diagnose", "television", ["TV_REMOTE_FAULT"]),
    Case("cục nóng không chạy", "diagnose", "air_conditioner", ["AC_OUTDOOR_FAN_MOTOR"]),
    Case("nắp bồn cầu bị bung", "diagnose", "toilet", ["TOILET_SEAT_BROKEN"]),
    Case("máy sấy mới mua mà sấy không khô bằng máy cũ", "diagnose", "clothes_dryer", ["DRYER_NOT_HEATING"]),
    Case("máy rửa bát chết nguồn", "diagnose", "dishwasher", ["DW_NO_POWER"]),
    Case("may rua bat bam khong an", "diagnose", "dishwasher", ["DW_NO_POWER"]),
    Case("tivi cứ tắt rồi bật", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("vòi nước nước phun lệch", "diagnose", "faucet", ["FAUCET_LOW_FLOW"]),
    Case("vòi nước bị rỉ", "diagnose", "faucet", ["FAUCET_DRIP"]),
    Case("vòi nước không chỉnh được nóng lạnh", "diagnose", "faucet", ["FAUCET_CARTRIDGE"]),
    Case("máy rửa bát rửa xong vẫn phải rửa lại bằng tay", "diagnose", "dishwasher", ["DW_NOT_CLEAN"]),
    Case("ổ điện chết", "diagnose", "power_outlet", ["OUTLET_NO_POWER"]),
    Case("ấm đun nước công tắc không bật lên", "diagnose", "kettle", ["KETTLE_THERMOSTAT"]),
    Case("bóng đèn buổi tối đèn yếu hẳn", "diagnose", "light_bulb", ["LIGHT_DIM"]),
    Case("khoa dien tu bao pin yeu", "diagnose", "smart_lock", ["LOCK_LOW_BATTERY"]),
    Case("ổ cắm điện gạt lên nó lại nhảy", "diagnose", "power_outlet", ["OUTLET_TRIPS_BREAKER"]),
    Case("đường ống nước cống bốc mùi", "diagnose", "water_pipe", ["PIPE_CLOGGED"]),
    Case("nút cảm ứng bếp từ không nhạy", "diagnose", "induction_hob", ["HOB_TOUCH_FAULT"]),
    Case("bình đun nước nhà em hứng cả tiếng chưa đầy", "diagnose", "water_purifier", ["PURIFIER_NO_WATER"]),
    Case("khóa cửa thông minh chắc cảm biến hỏng rồi", "diagnose", "smart_lock", ["LOCK_FINGERPRINT_FAIL"]),
    Case("quạt trần kêu ù ù", "diagnose", "ceiling_fan", ["CEILFAN_BEARING"]),
    Case("lò nướng chuông lò không reo", "diagnose", "oven", ["OVEN_TIMER_FAULT"]),
    Case("máy rửa bát chắc phải dùng nước rửa chén xịn hơn", "diagnose", "dishwasher", ["DW_NOT_CLEAN"]),
    Case("quạt điện quạt bị đơ", "diagnose", "electric_fan", ["FAN_CAPACITOR"]),
    Case("vòi nước vòi gạt không êm", "diagnose", "faucet", ["FAUCET_CARTRIDGE"]),
    Case("bồn cầu nghe róc rách cả đêm không ngủ được", "diagnose", "toilet", ["TOILET_FLAPPER_LEAK"]),
    Case("máy rửa bát chảy nước ra cửa", "diagnose", "dishwasher", ["DW_DOOR_LEAK"]),
    Case("bồn cầu nghe ù ù trong nhà vệ sinh", "diagnose", "toilet", ["TOILET_FLAPPER_LEAK"]),
    Case("bếp gas núm vặn kẹt", "diagnose", "gas_stove", ["STOVE_VALVE_STUCK"]),
    Case("tivi màu sắc bị sai", "diagnose", "television", ["TV_MAIN_BOARD"]),
    Case("lò vi sóng lò kêu ầm ầm", "diagnose", "microwave_oven", ["MW_FAN_NOISY"]),
    Case("máy lọc nước chảy rất chậm", "diagnose", "water_purifier", ["PURIFIER_NO_WATER"]),
    Case("quạt trần phải bật số 3 mới chạy", "diagnose", "ceiling_fan", ["CEILFAN_CAPACITOR"]),
    Case("bồn rửa rửa bát mà nước dâng lên", "diagnose", "sink", ["SINK_CLOGGED"]),
    Case("may say keu cach cach", "diagnose", "clothes_dryer", ["DRYER_NOISY"]),
    Case("bóng đèn nổ", "diagnose", "light_bulb", ["LIGHT_BULB_DEAD"]),
    Case("quạt trần yếu xìu", "diagnose", "ceiling_fan", ["CEILFAN_CAPACITOR"]),
    Case("khóa cửa thông minh hết pin rồi làm sao", "diagnose", "smart_lock", ["LOCK_LOW_BATTERY"]),
    Case("vòi nước gạt hết cỡ vẫn chảy", "diagnose", "faucet", ["FAUCET_CARTRIDGE"]),
    Case("quạt điện quạt không lắc đầu nữa", "diagnose", "electric_fan", ["FAN_OSCILLATION_FAULT"]),
    Case("máy rửa bát bát còn dính cơm ở đáy", "diagnose", "dishwasher", ["DW_NOT_CLEAN"]),
    Case("lò vi sóng chốt cửa bị gãy", "diagnose", "microwave_oven", ["MW_DOOR_SWITCH"]),
    Case("bếp từ em tra mạng thấy E1 là quá nhiệt", "diagnose", "induction_hob", ["HOB_ERROR_CODE"]),
    Case("máy lạnh không lạnh", "diagnose", "air_conditioner", ["AC_LOW_REFRIGERANT"]),
    Case("máy sấy dạo này kêu to hơn trước", "diagnose", "clothes_dryer", ["DRYER_NOISY"]),
    Case("lò vi sóng mâm bị lệch", "diagnose", "microwave_oven", ["MW_TURNTABLE_MOTOR"]),
    Case("ống nước rên", "diagnose", "water_pipe", ["PIPE_NOISY"]),
    Case("quạt điện dây quạt bị sờn", "diagnose", "electric_fan", ["FAN_CORD_DAMAGE"]),
    Case("ống nước bị đứt", "diagnose", "water_pipe", ["PIPE_BURST"]),
    Case("bồn cầu nước chảy lờ đờ", "diagnose", "toilet", ["TOILET_WEAK_FLUSH"]),
]
